framework:
    messenger:
        transports:
            new_report_consumer:
                dsn: '%env(KAFKA_URL)%'
                serializer: App\MessageSerializer\NewReportSerializer
                options:
                    commitAsync: true
                    receiveTimeout: 10000
                    topic:
                        name: 'new-reports'
                    kafka_conf:
                        enable.auto.offset.store: 'false'
                        group.id: 'group-statistics-products' # should be unique per consumer
                        security.protocol: 'plaintext' #'sasl_ssl'
                        max.poll.interval.ms: '45000'
                    topic_conf:
                        auto.offset.reset: 'earliest'

        routing:
            App\Message\Consume\NewReport\NewReportMessage: new_report_consumer
