framework:
    messenger:
        transports:
            new_order_consumer:
                dsn: '%env(KAFKA_URL)%'
                serializer: App\MessageSerializer\NewOrderSerializer
                options:
                    commitAsync: true
                    receiveTimeout: 10000
                    topic:
                        name: 'new-orders'
                    kafka_conf:
                        enable.auto.offset.store: 'false'
                        group.id: 'group-delivery-order-status' # should be unique per consumer
                        security.protocol: 'plaintext'
                        max.poll.interval.ms: '45000'
                    topic_conf:
                        auto.offset.reset: 'earliest'
            order_status_producer:
                dsn: '%env(KAFKA_URL)%'
                serializer: App\MessageSerializer\UpdateOrderStatusSerializer
                options:
                    flushTimeout: 10000
                    flushRetries: 5
                    topic:
                        name: 'order-status'
                    kafka_conf:
                        security.protocol: 'plaintext'

        routing:
            App\Message\Produce\UpdateOrderStatusMessage: order_status_producer
            App\Message\Consume\NewOrder\NewOrderMessage: new_order_consumer
