framework:
    messenger:
        transports:
            new_user_consumer:
                dsn: '%env(KAFKA_URL)%'
                serializer: App\MessageSerializer\NewUserSerializer
                options:
                    commitAsync: true
                    receiveTimeout: 10000
                    topic:
                        name: 'users'
                    kafka_conf:
                        enable.auto.offset.store: 'false'
                        group.id: 'group-notification-order-status'
                        security.protocol: 'plaintext'
                        max.poll.interval.ms: '45000'
                    topic_conf:
                        auto.offset.reset: 'earliest'
            new_order_consumer:
                dsn: '%env(KAFKA_URL)%'
                serializer: App\MessageSerializer\NewOrderSerializer
                options:
                    commitAsync: true
                    receiveTimeout: 10000
                    topic:
                        name: 'new-orders'
                    kafka_conf:
                        enable.auto.offset.store: 'false'
                        group.id: 'group-notification-new-orders'
                        security.protocol: 'plaintext'
                        max.poll.interval.ms: '45000'
                    topic_conf:
                        auto.offset.reset: 'earliest'

        routing:
            App\Message\Consume\NewUserMessage: new_user_consumer
            App\Message\Consume\NewOrder\NewOrderMessage: new_order_consumer
