framework:
    messenger:
        transports:
            product_producer:
                dsn: '%env(KAFKA_URL)%'
                serializer: App\MessageSerializer\ProductSerializer
                options:
                    flushTimeout: 10000
                    flushRetries: 5
                    topic:
                        name: 'products'
                    kafka_conf:
                        security.protocol: 'plaintext'
        routing:
            App\Message\Produce\Product\ProductMessage: product_producer
