framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
            user_sign_up_producer:
                dsn: '%env(KAFKA_URL)%'
                serializer: App\MessageSerializer\UserSignUpSerializer
                options:
                    flushTimeout: 10000
                    flushRetries: 5
                    topic:
                        name: 'users'
                    kafka_conf:
                        security.protocol: 'plaintext' #'sasl_ssl'
#                        ssl.ca.location: '%kernel.project_dir%/config/kafka/ca.pem'
#                        sasl.username: '%env(KAFKA_SASL_USERNAME)%'
#                        sasl.password: '%env(KAFKA_SASL_PASSWORD)%'
#                        sasl.mechanisms: 'SCRAM-SHA-256'
            product_consumer:
                dsn: '%env(KAFKA_URL)%'
                serializer: App\MessageSerializer\ProductSerializer
                options:
                    commitAsync: true
                    receiveTimeout: 10000
                    topic:
                        name: 'products'
                    kafka_conf:
                        enable.auto.offset.store: 'false'
                        group.id: 'group-products' # should be unique per consumer
                        security.protocol: 'plaintext' #'sasl_ssl'
#                        ssl.ca.location: '%kernel.project_dir%/config/kafka/ca.pem'
#                        sasl.username: '%env(KAFKA_SASL_USERNAME)%'
#                        sasl.password: '%env(KAFKA_SASL_PASSWORD)%'
#                        sasl.mechanisms: 'SCRAM-SHA-256'
                        max.poll.interval.ms: '45000'
                    topic_conf:
                        auto.offset.reset: 'earliest'
            order_status_consumer:
                dsn: '%env(KAFKA_URL)%'
                serializer: App\MessageSerializer\UpdateOrderStatusSerializer
                options:
                    commitAsync: true
                    receiveTimeout: 10000
                    topic:
                        name: 'order-status'
                    kafka_conf:
                        enable.auto.offset.store: 'false'
                        group.id: 'group-order-status' # should be unique per consumer
                        security.protocol: 'plaintext'
                        max.poll.interval.ms: '45000'
                    topic_conf:
                        auto.offset.reset: 'earliest'

        routing:
            App\Message\Product: product_consumer
            App\Message\UserSignUp: user_sign_up_producer
            App\Message\UpdateOrderStatus: order_status_consumer

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
